### ISSUE TITLE
replay or loop

### ISSUE THREAD

**Issue by serhatkimya** [nitpum/MMM-EmbedYoutube#1]
hi, i wanna learn how can i loop a youtube video?  is there code? thanks.

**Comment by nitpum** [comment]
I added loop options. You just update module and add ``loop: true`` to ``config.js`` file your video will auto play again when it end.

P.S. I update some config option to match Youtube iFrame API so you may need to update some config.

**Comment by serhatkimya** [comment]
thanks very much

**Comment by nitpum** [comment]
If you have a problem or found a bug or have a suggested idea you can tell me. :)
