### ISSUE TITLE
Video not displaying

### ISSUE THREAD

**Issue by Jord7529** [nitpum/MMM-EmbedYoutube#11]
Hello,

I am trying to have a Youtube video to be displayed the in the bottom right corner of my screen

Here's my config:
{
		module: "MMM-EmbedYoutube", 
		disabled: false,		
		position: "bottom_right",	
		config: {
			video_id: "lrX6ktLg8WQ",
			loop: true,
			autoplay: true,
			height: 300,
			width: 450
		}
	},

Am I doing something wrong as the video isn't attempting to display

**Comment by Jord7529** [comment]
I have now got this working, spelling mistake in another file! I do still have one issue though and that is I am unable to get the AutoPlay to work the video loads but won't play unless you physically click the play button. Any ideas?

**Comment by nitpum** [comment]
What version MagicMirror and module you use?
