### ISSUE TITLE
Youtube video not showing up 

### ISSUE THREAD

**Issue by SebastianNewToThis** [nitpum/MMM-EmbedYoutube#13]
Hello, Im verry new to this and im trying to get a youtube video to display on my magicmirror but it is not showing up. could you see what went wrong?
{
			module: "calendar",
			header: "Swedish Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://www.officeholidays.com/ics/sweden"					}
				]
			}
		},
		{
		    module: "MMM-EmbedYoutube", // Path to youtube module from modules folder Exmaple: MagicMirror/modules/custom/MMM-EmbedYoutube/ so it's custom/MMM-EmbedYoutube
		    position: "middle_center",	// This can be any of the regions.
		    config: {
                     autoplay: true,
	   	             color: "red",
		             controls : true,
		             disablekb: false,
		             fs: true,
		             height: 315,
		             width: 560,
	                 loop: true,
		             modestbranding: false,
		             rel : false,
		             showinfo : true,
		             video_id : "TpNvKY-l_2c",
		             playlist: "",
		             video_list: []
		   }
	    },
		{
			module: "compliments",
			position: "bottom_bar"
		},

**Comment by nitpum** [comment]
@SebastianNewToThis 
Remove playlist and video_list from config.
You don't need to set playlist in config file if you set it, it will neither play video from video_id nor video_list

**Comment by SebastianNewToThis** [comment]
![Skärmklipp](https://user-images.githubusercontent.com/53217891/61776711-e01e7600-adfb-11e9-95e9-59a0f60f6ba8.PNG)

I tried to remove it but there is still no video showing up on the MagicMirror

**Comment by nitpum** [comment]
@SebastianNewToThis  Can you give me a screenshot of MagicMirror.
What did it show?
Where did you install MMM-EmbedYoutube?

**Comment by SebastianNewToThis** [comment]
![image](https://user-images.githubusercontent.com/53217891/61786804-c9cde580-ae0e-11e9-9949-1c763cd2e3a7.png)

**Comment by SebastianNewToThis** [comment]
![image](https://user-images.githubusercontent.com/53217891/61786852-dfdba600-ae0e-11e9-8406-e73be9dc1fa1.png)

**Comment by nitpum** [comment]
@SebastianNewToThis  Ok, You installed module at `MagicMirror/module/MMM-EmbedYoutube-master`
so in config file module should be `MMM-EmbedYoutube-master`
instead of 
```json
{
 module: "MMM-EmbedYoutube"
```
change to this
```json
{
 module: "MMM-EmbedYoutube-master"
```

**Comment by SebastianNewToThis** [comment]
![image](https://user-images.githubusercontent.com/53217891/61824752-16411180-ae5f-11e9-9255-4b31239b1295.png)

Thank you for your help, I tried to do as you said but it is still not showing up. The MagicMirror screen still look like the picture above.

**Comment by nitpum** [comment]
@SebastianNewToThis 
Rename `MMM-EmbedYoutube-master` folder to `MMM-EmbedYoutube`
and change config back to
```json
{
  module: "MMM-EmbedYoutube"
```

**Comment by SebastianNewToThis** [comment]
Thank you, it is working now. one last question, how do I get it to autoplay direct when I start MagicMirror. As you can see in my config above "autoplay" is set to "true".

**Comment by nitpum** [comment]
@SebastianNewToThis from #12 look likes new Electron version has policy that  disable autoplay by default
You can fix it by following this instruction https://forum.magicmirror.builders/topic/10556/youtube-autoplay/2
