### ISSUE TITLE
ERROR! Could not find main module js file for MMM-EmbedYoutube

### ISSUE THREAD

**Issue by gmglickman** [nitpum/MMM-EmbedYoutube#2]
Have never gotten this working. Clean reinstall. 
youtube.js exists in ~/MagicMirror/modules/MMM-EmbedYoutube. 

config.js includes      module: "/MMM-EmbedYoutube",

Am I missing something? Thanks.

**Comment by nitpum** [comment]
Hi @gmglickman, Thank for reporting. It because file name and module name doesn't match each other.
Now I fixed it with v1.2.2. You just update module to the latest version.
