### ISSUE TITLE
I can see that this code is used to play a single video... How do I get it to play a play list?

### ISSUE THREAD

**Issue by justjim1220** [nitpum/MMM-EmbedYoutube#4]
If someone could help me convert the following code into a module, and tweak it to work by inserting just the playlist ID............

Here is the code I need to work as a module in MagicMirror…

var player;

function onYouTubeIframeAPIReady() {
player = new YT.Player(‘video-placeholder’, {
width: 600,
height: 400,
videoId: ‘’,
playerVars: {
color: ‘white’,
playlist: ‘’
},
events: {
onReady: initialize
}
});
}

function initialize(){

// Update the controls on load
updateTimerDisplay();
updateProgressBar();

// Clear any old interval.
clearInterval(time_update_interval);

// Start interval to update elapsed time display and
// the elapsed part of the progress bar every second.
time_update_interval = setInterval(function () {
updateTimerDisplay();
updateProgressBar();
}, 1000)
}

/ This function is called by initialize()
function updateTimerDisplay(){
// Update current time text display.
$(’#current-time’).text(formatTime( player.getCurrentTime() ));
$(’#duration’).text(formatTime( player.getDuration() ));
}

function formatTime(time){
time = Math.round(time);

var minutes = Math.floor(time / 60),
seconds = time - minutes * 60;

seconds = seconds < 10 ? '0' + seconds : seconds;

return minutes + ":" + seconds;
}

$(’#progress-bar’).on(‘mouseup touchend’, function (e) {

// Calculate the new time for the video.
// new time in seconds = total duration in seconds * ( value of range input / 100 )
var newTime = player.getDuration() * (e.target.value / 100);

// Skip video to new time.
player.seekTo(newTime);
});

// This function is called by initialize()
function updateProgressBar(){
// Update the value of our progress bar accordingly.
$(’#progress-bar’).val((player.getCurrentTime() / player.getDuration()) * 100);
}

$(’#play’).on(‘click’, function () {

player.playVideo();
});

$(’#pause’).on(‘click’, function () {

player.pauseVideo();
});

$(’#mute-toggle’).on(‘click’, function() {
var mute_toggle = $(this);

if(player.isMuted()){
player.unMute();
mute_toggle.text('volume_up');
}
else{
player.mute();
mute_toggle.text('volume_off');
}
});

$(’#volume-input’).on(‘change’, function () {
player.setVolume($(this).val());
});

// To get the current volume of the player use this method:
// player.getVolume()

$(’#speed’).on(‘change’, function () {
player.setPlaybackRate($(this).val());
});

// To get the current playback rate for a video use this method:
// player.getPlaybackRate()

// To get all available playback rates for the current video use:
// player.getAvailablePlaybackRates()

$(’#quality’).on(‘change’, function () {
player.setPlaybackQuality($(this).val());
});

// To get the actual video quality of the running video use this method:
// player.getPlaybackQuality()

// To get a list of the available quality formats for a video use:
// player.getAvailableQualityLevels()

$(’#next’).on(‘click’, function () {
player.nextVideo()
});

$(’#prev’).on(‘click’, function () {
player.previousVideo()
});

$(’.thumbnail’).on(‘click’, function () {

var url = $(this).attr('data-video-id');

player.cueVideoById(url);
});

What I am trying to do is to get a YouTube player to play an existing playlist, without having to list each individual video but, just by using the playlist ID. For example, this is my personal playlist…

https://www.youtube.com/playlist?list=PLl_KM23gznEAZW-INW8ty4QNaHH8JCnNW

I should be able to just input a playlist ID (PLl_KM23gznEAZW-INW8ty4QNaHH8JCnNW) and have it play, using autostart and loop and shuffle…

Any help with getting this figured out will be MUCH appreciated!!!
Thanks to anyone who helps in advance!!!

**Comment by justjim1220** [comment]
another code that I could use if able to be converted to work in the MM is found here...

https://github.com/nirvanatikku/jQuery-TubePlayer-Plugin

**Comment by nitpum** [comment]
I'm working on it

**Comment by justjim1220** [comment]
I got it to work using MMM-iFrame...

{
		module: 'MMM-iFrame',
		position: 'bottom_bar',	// This can be any of the regions.
		config: {
			// See 'Configuration options' for more information.
				url: ["https://www.youtube.com/playlist?list=PLl_KM23gznEAZW-INW8ty4QNaHH8JCnNW"],  // ["ENTER IN URL", "ENTER IN URL2"] as many URLs you want or you can just ["ENTER IN URL"] if single URL.
				//updateInterval: 0.5 * 60 * 1000, // rotate URLs every 30 seconds
				width: "720px", // Optional. Default: 100%
				height: "480px" //Optional. Default: 100px
			}
		}
	}

But I would still like to get it to shuffle automatically - still trying to figure that part out...

**Comment by nitpum** [comment]
@justjim1220 MMM_EmbedYoutube v1.3.0 now supported playlist. You can use playlist ID.
In config like this
```js
"playlist": "PLl_KM23gznEAZW-INW8ty4QNaHH8JCnNW"
```
I'm trying to implement the shuffle and Youtube-API it take a time because I'm too busy.
