### ISSUE TITLE
Autoplay does not work

### ISSUE THREAD

**Issue by Hellangel1987** [nitpum/MMM-EmbedYoutube#5]
Im trying to implement a Video with autoplay:
https://www.youtube.com/watch?v=vr3mTas9I8I

if i implement it with your Options Autoplay = True and Co. it only shows video but does not start.

`
/* Magic Mirror
 * Module: Embed Youtube
 * 
 * v 1.2.1
 * 
 * By Nitipoom Unrrom (aka nitpum) https://nitpum.com
 * MIT Licensed.
 */
Module.register("MMM-EmbedYoutube", {
	defualts: {
		autoplay: true,
		color: "red",
		controls : false,
		disablekb: false,
		fs: false,
		height: 630,
		width: 1020,
		loop: true,
		modestbranding: false,
		rel : false,
		showinfo : false,
		video_id : "vr3mTas9I8I",
	},
	getDom: function () {
		var wrapper = document.createElement("div");

		// Parameter
		var params = "?";
		params += (this.config.autoplay) ?"autoplay=1" : "autoplay=0";
		params += (this.config.color != "red")? "&color=" + this.config.color:"";
		params += (this.config.controls)? "&controls=1":"&controls=0";
		params += (this.config.disablekb)? "&disablekb=1":"";
		params += (this.config.fs)? "":"&fs=0";
		params += (this.config.loop) ? "&loop=1&playlist=" + this.config.video_id : "";
		params += (this.config.modestbranding) ? "&modestbranding=1" : "";
		params += (this.config.rel)? "&rel=1": "&rel=0";
		params += (this.config.showinfo)? "&showinfo=1": "&showinfo=0";

		wrapper.innerHTML = "<iframe width=\"" + this.config.width +"\" height=\"" + this.config.height + "\" src=\"https://www.youtube.com/embed/" + this.config.video_id+params +"\" frameborder=\"0\" allowfullscreen></iframe>";
		return wrapper;
	}
});
`

As seen here other Users have simillar issues with autoplay:
https://stackoverflow.com/questions/40685142/youtube-autoplay-not-working

Thank you for any Hint on this

**Comment by nitpum** [comment]
@Hellangel1987 It not working because you set config in the module file.
you need to set config in `config/config.js` not in `MMM-EmbedYoutube/MMM-EmbedYoutube.js`
