### ISSUE TITLE
Video not found or error on video

### ISSUE THREAD

**Issue by RafaelCota** [nitpum/MMM-EmbedYoutube#9]
Hi,
I'm using MMM-EmbedYoutube to play Live streaming videos, but sometimes the video just doesn't load and the player doesn't skip to the next in the list, ¿is there a way to make it go to the next one?

Thank's in advanced,

config.js
-----
                     {
                        disabled: false,
                        module: "MMM-EmbedYoutube",
                        position: "lower_third",
                        config: {
                                video_id: "ovmSF0RIwTQ", // Mr. Bean
                                video_list: [
                                        "XqBByfhehS8", // CNN Español
                                        "ZIjBESJc0gw", // Milenio TV
                                        "XOacA3RYrXk", // Sky News Sports
                                        "7hbAIHIdcko", // ABC News
                                        "lzlVZ8QQbDg", // CNN News
                                ],
                                autoplay: true,
                                loop: true,
                                height: 300,
                                width: 450
                        }
                },

**Comment by nitpum** [comment]
Hi, I release a new version now please update the module.
Normally, Youtube will auto play the next video in the list when the video is ended
but Live streaming have a long length if you want to skip without wait it's ended, you have to click the skip button manually
